### ISSUE TITLE
Confusión en instrucciones de creación del pen de arranque

### ISSUE THREAD

**Issue by chipygr** [aosucas499/lamentablet-vexia#1]
Buenos dias, en uno de los primeros pasos ya veo un posible motivo de confusión.
Se dice que se descomprima el archivo .tz en la raiz del pendrive, cuando si se hace eso, nos dará lugar a tener en la raiz del pen un archivo .tar, que creo, no es lo que queremos tener en él, no?

**Comment by aosucas499** [comment]
Buenas compañero. ¿Te refieres al pdf de la junta de Andalucía o a el apartado de la wiki de investigación al crear el sistema?

**Comment by chipygr** [comment]
En el de la junta. Perdona no he escrito el cuerpo de lo que queria por invasion de un peque y lo estaba editando

**Comment by aosucas499** [comment]
Vale, le echo un vistazo. Es el mismo que se utilizaba para Guadalinex anteriormente. Solo cambia el nombre de mi archivo. ¿Alguna recomendación? ¿Cambiarlo entero o solo los nombres de los archivos nuevos?

**Comment by chipygr** [comment]
Estoy en el proceso de descompresión en el pen, tarda lo suyo... Cuando lo subiste al Drive, iba comprimido dos veces? porque?

**Comment by aosucas499** [comment]
No iba comprimido dos veces, voy a revisarlo pero creo que no.

**Comment by chipygr** [comment]
Es que no tiene logica, y está igual que el archivo de actualizacion, están mal las instrucciones (según entiendo yo...) Se descomprime el .tz y luego el .tar, no? pero segun las instrucciones solo descomprimes el .tz

**Comment by jaimecarrascogarcia** [comment]
Chicos...el archivo esta perfecto, ya he probado hoy una de 9v y va perfecto. Lo he descomprimido con winrar....

PD: He hecho lo que te comenté en la BIOS UEFI,  ANDRÉS y todo perfecto, era eso....(para que iniciara del tirón)

**Comment by aosucas499** [comment]
Es que es raro que te salgan dos archivos, uno dentro de otro. Voy a revisarlo vaya que linux haya hecho una doble compresión.

**Comment by aosucas499** [comment]
> Chicos...el archivo esta perfecto, ya he probado hoy una de 9v y va perfecto. Lo he descomprimido con winrar....
> 
> PD: He hecho lo que te comenté en la BIOS UEFI, ANDRÉS y todo perfecto, era eso....(para que iniciara del tirón)

Genial, lo tendremos en cuenta en las instrucciones.

**Comment by chipygr** [comment]
voy a probar, yo la primera lo he descomprimido con 7z, a ver si va a ser eso

**Comment by chipygr** [comment]
ahora lo está haciendo del tirón... problema del 7z (o mio...)

**Comment by aosucas499** [comment]
> ahora lo está haciendo del tirón... problema del 7z (o mio...)

Cierro problema entonces

**Comment by aosucas499** [comment]
Ya tenemos instrucciones propias [aquí](https://github.com/aosucas499/lamentablet-vexia/wiki/0.-Instrucciones-de-instalaci%C3%B3n-MININO-%23TDE-en-tablets-VEXIA) y el archivo comprimido en .zip para solucionar problemas en windows
