### ISSUE TITLE
Automatizar aplicaciones al inicio

### ISSUE THREAD

**Issue by madoju78** [aosucas499/lamentablet-vexia#2]
Buenas, estoy configurando una tablet d cargador negro con minino instalado como punto de acceso del control de presencia de Séneca. ¿cómo puedo hacer que encendiendo la tablet, se lance Firefox? 
Gracias y gran trabajo

**Comment by aosucas499** [comment]
Buenos días.
1. En el menú inicio, apartado "Preferencias", busca "Aplicaciones predeterminadas para Lxsession".
2. Al abrir la aplicación, a la izquierda tienes cuatro opciones, pulsa en "autostart".
3. A la derecha, busca un signo + en color verde con la inscripción "Añadir" y un cuadro de texto para que añadas lo que quieres que se inicie en cada encendido. 
4. Pega esta dirección en el cuadro de texto:
   `/usr/lib/firefox-latest/firefox`
5. Pulsa en el signo + verde con la inscripción "Añadir"

![VirtualBox_minino TDE_14_03_2021_11_34_42](https://user-images.githubusercontent.com/72696244/111065445-ff2eb780-84b9-11eb-9451-96f331ae3bc2.png)

Cuéntame que tal les va a los profes usándolo cuando lo instales, estoy pensando en ponerlo en mi centro cuando esté activo el módulo de presencia en mi centro.

**Comment by madoju78** [comment]
Vale. Hecho sin problemas. La cuestión es que no se puede automatizar del todo o no doy con la tecla. Arranca Firefox pero da la siguiente imagen. 
![20210315_144822](https://user-images.githubusercontent.com/78934460/111211115-4e660c80-85ce-11eb-8c99-6e164be9c03d.jpg)





Es como si tardara en actualizar la hora pq le doy a Reintentar a los 20 segundos o así y ya sale la página d control de presencia y va perfectamente. Pero claro esos 20 segundos hay que esperar y darle manualmente al botón. No sé si podrá automatizar ese refresco. 
Otro tema: las opciones d energía y suspensión d pantalla dónde andan?? 
Seguimos d pruebas. Gracias!

**Comment by aosucas499** [comment]
Minino lleva un script que actualiza la hora por internet porque da fallo sino se hace sobretodo en Andared. Habría que lanzar firefox 20 segundos después. Prueba a lanzarlo 30 segundos después. En el cuadro de texto donde pusiste firefox, cambia por esto :

sleep 30 && /usr/lib/firefox-latest/firefox

**Comment by madoju78** [comment]
Hola. No sé si estoy escribiendo mal el comando. No hace nada :(

**Comment by aosucas499** [comment]
Olvídate de lo anterior. 

Abre una terminal y escribe los siguientes comandos:

```
wget https://raw.githubusercontent.com/aosucas499/minino-TDE/main/tools/Firefox-latest-sleep30

sudo cp Firefox-latest-sleep30 /etc/xdg/autostart/Firefox-latest-sleep30.desktop
```

**Comment by aosucas499** [comment]
Aquí te pongo algunas recomendaciones para el uso del control de presencia, al final de la página.

[wiki-control de presencia](https://github.com/aosucas499/lamentablet-vexia/wiki/FAQ's)

Cuéntame qué tal te va y si carga bien cuando lo pruebes.

**Comment by madoju78** [comment]
Perfecto. Voy a probar simplemente por ver si funciona. Aunque la hemos estado probando encendiendo a mano y por el tema del táctil, tengo casi desechada usarla. Cuesta mucho, arrastrar y meterse en el teclado pars pin. Mejor dicho, a los compis no se les hace fácil. Así que casi seguro que pasemos a una vexia d cargador blanco con guadalinex edu.
Muchas gracias x la ayuda!! Seguimos con minino a tope

**Comment by madoju78** [comment]
Hola. Hoy la he probado por ver cómo iba y la orden va perfecta. Firefox arranca cuando ya está ajustada la hora directamente al control d presencia. Así que va genial!
A pesar d ello, en mi centro hemos terminado usando una Vexia de cargador blanco con Guadalinex Edu pq los compis no se terminaban d adaptar a la forma especial que se le ha quedado al táctil con Minino.
Muchas gracias x todo!

**Comment by aosucas499** [comment]
Genial. Gracias por el feedback.
